version: "3.8"

services:
  larvis-service:
    build:
      context: ./larvis-service
    ports:
      - "8080:8080"
    container_name: larvis-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  larvis-ui:
    build:
      context: ./larvis-ui
    ports:
      - "3000:3000"
    container_name: larvis-ui
    depends_on:
      - larvis-service
    volumes:
      - ./larvis-ui:/app
      - larvis_node_modules:/app/node_modules
    environment:
      - NODE_OPTIONS=--no-deprecation
      - CHOKIDAR_USEPOLLING=true
    command: ["yarn", "dev"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/login"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  larvis_node_modules: {}